### ISSUE TITLE
Chart doesnt render in iOS or Android

### ISSUE THREAD

**Issue by sanziosan** [EddyVerbruggen/nativescripthighcharts#1]
I downloaded the latest copy of the source and ran it but the page doesnt seem to be rendering the chart. I see the text labels that say "Heres a graph for ya" but underneath the text is just blank. Same goes for the second graph.

**Comment by EddyVerbruggen** [comment]
Could be some things changed over the last 9 months. Do you see this with NativeScript 3 and 4?

**Comment by sanziosan** [comment]
nativescript --version 
shows:
3.4.3

Ive tried other chart examples and they have been working just fine

**Comment by EddyVerbruggen** [comment]
Thanks!

Just updated the repo. It's prolly best to clone again, run `npm i`, and `tns run ios`.
